apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-hp
  labels:
    type: hostPath
    environment: Dev
spec:
  storageClassName: hostPath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp"
