apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-demo-rc

spec:
  replicas: 3
  selector:
    matchLabels:
      environment: production
  template:      #POD Template
    metadata:
      name: nginx-demo
      labels:
        app: nginx
        environment: production
        release: v1.0
    spec:
      containers:
        - name: write-container
          image: alpine
          command: ["/bin/sh"] #Passing command by using shell
          args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
          volumeMounts:
            - mountPath: /var/log
              name: shared-data
        - name: serving-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: shared-data
      volumes:
        - name: shared-data
          emptyDir: {}
            
