apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports: 
  - name: http
    port: 8161
    nodePort: 30010

  - name: endpoint
    port: 61616
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: fleetman-position-tracker
  ports: 
  - name: http
    port: 8080

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: fleetman-api-gateway
  ports: 
  - name: http
    port: 8080

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
spec:
  selector:
    app: fleetman-web-app
  ports: 
  - name: http
    port: 80
    nodePort: 30050

  type: NodePort
  
