apiVersion: batch/v1
kind: Job
metadata:
  name: demo-backup
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:8
        command: ["/bin/sh", "-c", "bash /tmp/mysql_backup_script.sh"]
        volumeMounts:
        - name: db-backup
          mountPath: /var/tmp
        - name: db-script
          mountPath: /tmp
      volumes:
      - name: db-backup
        hostPath:
          path: /var/tmp/db_backups
          type: DirectoryOrCreate
      - name: db-script
        configMap:
          name: db-backup-script
          items:
          - key: db_backup.sh
            path: mysql_backup_script.sh

      restartPolicy: OnFailure
