apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  template: 
    metadata:
      labels:
        app: nginx
        environment: production
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        ports:
          - containerPort: 80
            protocol: TCP
            name: http
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-data
  volumeClaimTemplates:
  - metadata:
      name: nginx-data
    spec:
      storageClassName: hostPath
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
          
