apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj-demo
spec:
  schedule: "*/2 * * * * "  #This will modify every 2 minute, hour, day, month & week
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ubuntu-demo
              image: ubuntu:22.04
              args: 
              - /bin/sh
              - c
              - date; echo hello world
          restartPolicy: OnFailure

              
    
