---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: <Paste the base64 encoded value of the CSR file> #encode the users csr with the command - cat akshay.csr | base64 -w 0. Copy and paste it under the request
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
